<?php
/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license. For more information, see
 * <http://www.doctrine-project.org>.
 */

namespace Doctrine\DBAL\Platforms\Keywords;

/**
 * Microsoft SQL Server 2000 reserved keyword dictionary.
 *
 * @license BSD http://www.opensource.org/licenses/bsd-license.php
 * @link    www.doctrine-project.com
 * @since   2.4
 * @author  Rodrigo Prado de Jesus <royopa@gmail.com>
 */
class SQLServer2000Keywords extends SQLServerKeywords
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'SQLServer2000';
    }

    /**
     * {@inheritdoc}
     * List of ODBC reserved keywords for SQL Server 2000
     * @link http://technet.microsoft.com/en-us/library/aa238507(v=sql.80).aspx
     */
    protected function getKeywords()
    {
        return array_merge(array_diff(parent::getKeywords(), array('DUMMY')), array(
            'ABSOLUTE',
            'EXEC',
            'OVERLAPS',
            'ACTION',
            'EXECUTE',
            'PAD',
            'ADA',
            'EXISTS',
            'PARTIAL',
            'ADD',
            'EXTERNAL',
            'PASCAL',
            'ALL',
            'EXTRACT',
            'POSITION',
            'ALLOCATE',
            'FALSE',
            'PRECISION',
            'ALTER',
            'FETCH',
            'PREPARE',
            'AND',
            'FIRST',
            'PRESERVE',
            'ANY',
            'FLOAT',
            'PRIMARY',
            'ARE',
            'FOR',
            'PRIOR',
            'AS',
            'FOREIGN',
            'PRIVILEGES',
            'ASC',
            'FORTRAN',
            'PROCEDURE',
            'ASSERTION',
            'FOUND',
            'PUBLIC',
            'AT',
            'FROM',
            'READ',
            'AUTHORIZATION',
            'FULL',
            'REAL',
            'AVG',
            'GET',
            'REFERENCES',
            'BEGIN',
            'GLOBAL',
            'RELATIVE',
            'BETWEEN',
            'GO',
            'RESTRICT',
            'BIT',
            'GOTO',
            'REVOKE',
            'BIT_LENGTH',
            'GRANT',
            'RIGHT',
            'BOTH',
            'GROUP',
            'ROLLBACK',
            'BY',
            'HAVING',
            'ROWS',
            'CASCADE',
            'HOUR',
            'SCHEMA',
            'CASCADED',
            'IDENTITY',
            'SCROLL',
            'CASE',
            'IMMEDIATE',
            'SECOND',
            'CAST',
            'IN',
            'SECTION',
            'CATALOG',
            'INCLUDE',
            'SELECT',
            'CHAR',
            'INDEX',
            'SESSION',
            'CHAR_LENGTH',
            'INDICATOR',
            'SESSION_USER',
            'CHARACTER',
            'INITIALLY',
            'SET',
            'CHARACTER_LENGTH',
            'INNER',
            'SIZE',
            'CHECK',
            'INPUT',
            'SMALLINT',
            'CLOSE',
            'INSENSITIVE',
            'SOME',
            'COALESCE',
            'INSERT',
            'SPACE',
            'COLLATE',
            'INT',
            'SQL',
            'COLLATION',
            'INTEGER',
            'SQLCA',
            'COLUMN',
            'INTERSECT',
            'SQLCODE',
            'COMMIT',
            'INTERVAL',
            'SQLERROR',
            'CONNECT',
            'INTO',
            'SQLSTATE',
            'CONNECTION',
            'IS',
            'SQLWARNING',
            'CONSTRAINT',
            'ISOLATION',
            'SUBSTRING',
            'CONSTRAINTS',
            'JOIN',
            'SUM',
            'CONTINUE',
            'KEY',
            'SYSTEM_USER',
            'CONVERT',
            'LANGUAGE',
            'TABLE',
            'CORRESPONDING',
            'LAST',
            'TEMPORARY',
            'COUNT',
            'LEADING',
            'THEN',
            'CREATE',
            'LEFT',
            'TIME',
            'CROSS',
            'LEVEL',
            'TIMESTAMP',
            'CURRENT',
            'LIKE',
            'TIMEZONE_HOUR',
            'CURRENT_DATE',
            'LOCAL',
            'TIMEZONE_MINUTE',
            'CURRENT_TIME',
            'LOWER',
            'TO',
            'CURRENT_TIMESTAMP',
            'MATCH',
            'TRAILING',
            'CURRENT_USER',
            'MAX',
            'TRANSACTION',
            'CURSOR',
            'MIN',
            'TRANSLATE',
            'DATE',
            'MINUTE',
            'TRANSLATION',
            'DAY',
            'MODULE',
            'TRIM',
            'DEALLOCATE',
            'MONTH',
            'TRUE',
            'DEC',
            'NAMES',
            'UNION',
            'DECIMAL',
            'NATIONAL',
            'UNIQUE',
            'DECLARE',
            'NATURAL',
            'UNKNOWN',
            'DEFAULT',
            'NCHAR',
            'UPDATE',
            'DEFERRABLE',
            'NEXT',
            'UPPER',
            'DEFERRED',
            'NO',
            'USAGE',
            'DELETE',
            'NONE',
            'USER',
            'DESC',
            'NOT',
            'USING',
            'DESCRIBE',
            'NULL',
            'VALUE',
            'DESCRIPTOR',
            'NULLIF',
            'VALUES',
            'DIAGNOSTICS',
            'NUMERIC',
            'VARCHAR',
            'DISCONNECT',
            'OCTET_LENGTH',
            'VARYING',
            'DISTINCT',
            'OF',
            'VIEW',
            'DOMAIN',
            'ON',
            'WHEN',
            'DOUBLE',
            'ONLY',
            'WHENEVER',
            'DROP',
            'OPEN',
            'WHERE',
            'ELSE',
            'OPTION',
            'WITH',
            'END',
            'OR',
            'WORK',
            'END-EXEC',
            'ORDER',
            'WRITE',
            'ESCAPE',
            'OUTER',
            'YEAR',
            'EXCEPT',
            'OUTPUT',
            'ZONE',
            'EXCEPTION'
        ));
    }
}
