<?php

declare(strict_types=1);

namespace Doctrine\DBAL\Driver;

use PDO;
use function assert;

/**
 * PDO implementation of the Connection interface.
 *
 * Used by all PDO-based drivers.
 */
class PDOConnection implements ServerInfoAwareConnection
{
    /** @var PDO */
    private $connection;

    /**
     * @param array<int, mixed> $options
     *
     * @throws PDOException In case of an error.
     */
    public function __construct(string $dsn, string $username = '', string $password = '', array $options = [])
    {
        try {
            $this->connection = new PDO($dsn, $username, $password, $options);
            $this->connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        } catch (\PDOException $exception) {
            throw PDOException::fromNativePDOException($exception);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function exec(string $statement) : int
    {
        try {
            return $this->connection->exec($statement);
        } catch (\PDOException $exception) {
            throw PDOException::fromNativePDOException($exception);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function getServerVersion() : string
    {
        return $this->connection->getAttribute(PDO::ATTR_SERVER_VERSION);
    }

    /**
     * {@inheritdoc}
     */
    public function prepare(string $sql) : Statement
    {
        try {
            return $this->createStatement(
                $this->connection->prepare($sql)
            );
        } catch (\PDOException $exception) {
            throw PDOException::fromNativePDOException($exception);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function query(string $sql) : ResultStatement
    {
        try {
            $stmt = $this->connection->query($sql);
            assert($stmt instanceof \PDOStatement);

            return $this->createStatement($stmt);
        } catch (\PDOException $exception) {
            throw PDOException::fromNativePDOException($exception);
        }
    }

    /**
     * {@inheritdoc}
     */
    public function quote(string $input) : string
    {
        return $this->connection->quote($input);
    }

    /**
     * {@inheritdoc}
     */
    public function lastInsertId()
    {
        try {
            $lastInsertId = $this->connection->lastInsertId();
        } catch (\PDOException $exception) {
            throw PDOException::fromNativePDOException($exception);
        }

        if (! $this->isValidLastInsertIdOrSequenceNumber($lastInsertId)) {
            throw new PDOException('No identity value was generated by the last statement.');
        }

        return $lastInsertId;
    }

    /**
     * {@inheritdoc}
     */
    public function getSequenceNumber(string $name)
    {
        try {
            $sequenceNumber = $this->connection->lastInsertId($name);
        } catch (\PDOException $exception) {
            throw PDOException::fromNativePDOException($exception);
        }

        if (! $this->isValidLastInsertIdOrSequenceNumber($sequenceNumber)) {
            throw new PDOException('No sequence with name "' . $name . '" found.');
        }

        return $sequenceNumber;
    }

    /**
     * @param int|string $value
     */
    private function isValidLastInsertIdOrSequenceNumber($value) : bool
    {
        // pdo_mysql & pdo_sqlite return 0 or '0', pdo_sqlsrv returns ''
        return $value !== 0 && $value !== '0' && $value !== '';
    }

    /**
     * {@inheritdoc}
     */
    public function requiresQueryForServerVersion() : bool
    {
        return false;
    }

    /**
     * Creates a wrapped statement
     */
    protected function createStatement(\PDOStatement $stmt) : PDOStatement
    {
        return new PDOStatement($stmt);
    }

    /**
     * {@inheritDoc}
     */
    public function beginTransaction() : void
    {
        $this->connection->beginTransaction();
    }

    /**
     * {@inheritDoc}
     */
    public function commit() : void
    {
        $this->connection->commit();
    }

    /**
     * {@inheritDoc}
     */
    public function rollBack() : void
    {
        $this->connection->rollBack();
    }

    public function getWrappedConnection() : PDO
    {
        return $this->connection;
    }
}
