<?php

declare(strict_types=1);

namespace Doctrine\DBAL\Platforms;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Platforms\Db2\Db2MetadataProvider;
use Doctrine\DBAL\Platforms\Exception\NotSupported;
use Doctrine\DBAL\Schema\ColumnDiff;
use Doctrine\DBAL\Schema\DB2SchemaManager;
use Doctrine\DBAL\Schema\Exception\UnspecifiedConstraintName;
use Doctrine\DBAL\Schema\Index;
use Doctrine\DBAL\Schema\Name\OptionallyQualifiedName;
use Doctrine\DBAL\Schema\Name\UnquotedIdentifierFolding;
use Doctrine\DBAL\Schema\PrimaryKeyConstraint;
use Doctrine\DBAL\Schema\TableDiff;
use Doctrine\DBAL\SQL\Builder\DefaultSelectSQLBuilder;
use Doctrine\DBAL\SQL\Builder\SelectSQLBuilder;
use Doctrine\DBAL\TransactionIsolationLevel;
use Doctrine\DBAL\Types\Types;
use Override;

use function array_merge;
use function count;
use function current;
use function implode;
use function sprintf;

/**
 * Provides the behavior, features and SQL dialect of the Db2 database platform of the oldest supported version.
 */
class DB2Platform extends AbstractPlatform
{
    public function __construct()
    {
        parent::__construct(UnquotedIdentifierFolding::UPPER);
    }

    #[Override]
    public function getBlobTypeDeclarationSQL(array $column): string
    {
        // todo blob(n) with $column['length'];
        return 'BLOB(1M)';
    }

    #[Override]
    protected function initializeDoctrineTypeMappings(): void
    {
        $this->doctrineTypeMapping = [
            'bigint'    => Types::BIGINT,
            'binary'    => Types::BINARY,
            'blob'      => Types::BLOB,
            'character' => Types::STRING,
            'clob'      => Types::TEXT,
            'date'      => Types::DATE_MUTABLE,
            'decimal'   => Types::DECIMAL,
            'double'    => Types::FLOAT,
            'integer'   => Types::INTEGER,
            'real'      => Types::SMALLFLOAT,
            'smallint'  => Types::SMALLINT,
            'time'      => Types::TIME_MUTABLE,
            'timestamp' => Types::DATETIME_MUTABLE,
            'varbinary' => Types::BINARY,
            'varchar'   => Types::STRING,
        ];
    }

    #[Override]
    protected function getBinaryTypeDeclarationSQLSnippet(?int $length): string
    {
        return $this->getCharTypeDeclarationSQLSnippet($length) . ' FOR BIT DATA';
    }

    #[Override]
    protected function getVarbinaryTypeDeclarationSQLSnippet(?int $length): string
    {
        return $this->getVarcharTypeDeclarationSQLSnippet($length) . ' FOR BIT DATA';
    }

    #[Override]
    public function getClobTypeDeclarationSQL(array $column): string
    {
        // todo clob(n) with $column['length'];
        return 'CLOB(1M)';
    }

    #[Override]
    public function getBooleanTypeDeclarationSQL(array $column): string
    {
        return 'SMALLINT';
    }

    #[Override]
    public function getIntegerTypeDeclarationSQL(array $column): string
    {
        return 'INTEGER' . $this->_getCommonIntegerTypeDeclarationSQL($column);
    }

    #[Override]
    public function getBigIntTypeDeclarationSQL(array $column): string
    {
        return 'BIGINT' . $this->_getCommonIntegerTypeDeclarationSQL($column);
    }

    #[Override]
    public function getSmallIntTypeDeclarationSQL(array $column): string
    {
        return 'SMALLINT' . $this->_getCommonIntegerTypeDeclarationSQL($column);
    }

    #[Override]
    protected function _getCommonIntegerTypeDeclarationSQL(array $column): string
    {
        if (! empty($column['autoincrement'])) {
            return ' GENERATED BY DEFAULT AS IDENTITY';
        }

        return '';
    }

    #[Override]
    public function getBitAndComparisonExpression(string $value1, string $value2): string
    {
        return 'BITAND(' . $value1 . ', ' . $value2 . ')';
    }

    #[Override]
    public function getBitOrComparisonExpression(string $value1, string $value2): string
    {
        return 'BITOR(' . $value1 . ', ' . $value2 . ')';
    }

    #[Override]
    protected function getDateArithmeticIntervalExpression(
        string $date,
        string $operator,
        string $interval,
        DateIntervalUnit $unit,
    ): string {
        switch ($unit) {
            case DateIntervalUnit::WEEK:
                $interval = $this->multiplyInterval($interval, 7);
                $unit     = DateIntervalUnit::DAY;
                break;

            case DateIntervalUnit::QUARTER:
                $interval = $this->multiplyInterval($interval, 3);
                $unit     = DateIntervalUnit::MONTH;
                break;
        }

        return $date . ' ' . $operator . ' ' . $interval . ' ' . $unit->value;
    }

    #[Override]
    public function getDateDiffExpression(string $date1, string $date2): string
    {
        return 'DAYS(' . $date1 . ') - DAYS(' . $date2 . ')';
    }

    #[Override]
    public function getDateTimeTypeDeclarationSQL(array $column): string
    {
        return 'TIMESTAMP(0)';
    }

    #[Override]
    public function getDateTypeDeclarationSQL(array $column): string
    {
        return 'DATE';
    }

    #[Override]
    public function getTimeTypeDeclarationSQL(array $column): string
    {
        return 'TIME';
    }

    #[Override]
    public function getTruncateTableSQL(string $tableName, bool $cascade = false): string
    {
        $parsedName = $this->parseOptionallyQualifiedName($tableName);

        return sprintf('TRUNCATE %s IMMEDIATE', $parsedName->toSQL($this));
    }

    #[Override]
    public function getSetTransactionIsolationSQL(TransactionIsolationLevel $level): string
    {
        throw NotSupported::new(__METHOD__);
    }

    #[Override]
    protected function getPrimaryKeyConstraintDeclarationSQL(PrimaryKeyConstraint $constraint): string
    {
        $this->ensurePrimaryKeyConstraintIsClustered($constraint);

        return parent::getPrimaryKeyConstraintDeclarationSQL($constraint);
    }

    #[Override]
    protected function supportsCommentOnStatement(): bool
    {
        return true;
    }

    #[Override]
    public function getCurrentDateSQL(): string
    {
        return 'CURRENT DATE';
    }

    #[Override]
    public function getCurrentTimeSQL(): string
    {
        return 'CURRENT TIME';
    }

    #[Override]
    public function getCurrentTimestampSQL(): string
    {
        return 'CURRENT TIMESTAMP';
    }

    #[Override]
    protected function _getCreateTableSQL(OptionallyQualifiedName $tableName, array $columns, array $parameters): array
    {
        $sql = parent::_getCreateTableSQL($tableName, $columns, $parameters);

        foreach ($parameters['indexes'] as $index) {
            $sql[] = $this->getCreateIndexSQL($index, $tableName->toSQL($this));
        }

        return $sql;
    }

    #[Override]
    public function getCreateIndexSQL(Index $index, string $tableName): string
    {
        $this->ensureIndexHasNoColumnLengths($index);
        $this->ensureIndexIsNotFulltext($index);
        $this->ensureIndexIsNotSpatial($index);
        $this->ensureIndexIsNotClustered($index);
        $this->ensureIndexIsNotPartial($index);

        return parent::getCreateIndexSQL($index, $tableName);
    }

    #[Override]
    public function getAlterTableSQL(TableDiff $diff): array
    {
        $sql         = [];
        $commentsSQL = [];

        $tableName    = $diff->getOldTable()->getObjectName();
        $tableNameSQL = $tableName->toSQL($this);

        foreach ($diff->getDroppedForeignKeyConstraintNames() as $constraintName) {
            $sql[] = $this->getDropForeignKeySQL($constraintName->toSQL($this), $tableNameSQL);
        }

        foreach ($diff->getDroppedIndexes() as $index) {
            $sql[] = $this->getDropIndexSQL($index->getObjectName()->toSQL($this), $tableNameSQL);
        }

        $droppedPrimaryKeyConstraint = $diff->getDroppedPrimaryKeyConstraint();

        if ($droppedPrimaryKeyConstraint !== null) {
            $constraintName = $droppedPrimaryKeyConstraint->getObjectName();

            if ($constraintName === null) {
                throw UnspecifiedConstraintName::forPrimaryKeyConstraint();
            }

            $sql[] = $this->getDropConstraintSQL($constraintName->toSQL($this), $tableNameSQL);
        }

        $queryParts = [];
        foreach ($diff->getAddedColumns() as $column) {
            $columnDef = $column->toArray();
            $queryPart = 'ADD COLUMN ' . $this->getColumnDeclarationSQL($columnDef);

            // Adding non-nullable columns to a table requires a default value to be specified.
            if (
                ! empty($columnDef['notnull']) &&
                ! isset($columnDef['default']) &&
                empty($columnDef['autoincrement'])
            ) {
                $queryPart .= ' WITH DEFAULT';
            }

            $queryParts[] = $queryPart;

            $comment = $column->getComment();

            if ($comment !== '') {
                $commentsSQL[] = $this->getCommentOnColumnSQL(
                    $tableNameSQL,
                    $column->getObjectName()->toSQL($this),
                    $comment,
                );
            }
        }

        $needsReorg = false;
        foreach ($diff->getDroppedColumns() as $column) {
            $queryParts[] =  'DROP COLUMN ' . $column->getObjectName()->toSQL($this);
            $needsReorg   = true;
        }

        foreach ($diff->getChangedColumns() as $columnDiff) {
            if ($columnDiff->hasCommentChanged()) {
                $newColumn     = $columnDiff->getNewColumn();
                $commentsSQL[] = $this->getCommentOnColumnSQL(
                    $tableNameSQL,
                    $newColumn->getObjectName()->toSQL($this),
                    $newColumn->getComment(),
                );
            }

            $this->gatherAlterColumnSQL(
                $tableNameSQL,
                $columnDiff,
                $sql,
                $queryParts,
                $needsReorg,
            );
        }

        if (count($queryParts) > 0) {
            $sql[] = 'ALTER TABLE ' . $tableNameSQL . ' ' . implode(' ', $queryParts);
        }

        $addedPrimaryKeyConstraint = $diff->getAddedPrimaryKeyConstraint();

        if ($addedPrimaryKeyConstraint !== null) {
            $sql[] = 'ALTER TABLE ' . $tableNameSQL . ' ADD '
                . $this->getPrimaryKeyConstraintDeclarationSQL($addedPrimaryKeyConstraint);
        }

        foreach ($diff->getAddedForeignKeys() as $foreignKey) {
            $sql[] = $this->getCreateForeignKeySQL($foreignKey, $tableNameSQL);
        }

        foreach ($diff->getAddedIndexes() as $index) {
            $sql[] = $this->getCreateIndexSQL($index, $tableNameSQL);
        }

        foreach ($diff->getIndexRenames() as $rename) {
            $sql[] = sprintf(
                'RENAME INDEX %s TO %s',
                $this->deriveQualifier($rename->getOldName(), $tableName)->toSQL($this),
                $rename->getNewIndex()->getObjectName()->toSQL($this),
            );
        }

        // Some table alteration operations require a table reorganization.
        if ($needsReorg) {
            $sql[] = sprintf("CALL SYSPROC.ADMIN_CMD ('REORG TABLE %s')", $tableNameSQL);
        }

        return array_merge($sql, $commentsSQL);
    }

    #[Override]
    public function getRenameTableSQL(string $oldName, string $newName): string
    {
        $parsedOldName = $this->parseOptionallyQualifiedName($oldName);
        $parsedNewName = $this->parseUnqualifiedName($newName);

        return sprintf(
            'RENAME TABLE %s TO %s',
            $parsedOldName->toSQL($this),
            $parsedNewName->toSQL($this),
        );
    }

    /**
     * Gathers the table alteration SQL for a given column diff.
     *
     * @param string       $table      The table to gather the SQL for.
     * @param ColumnDiff   $columnDiff The column diff to evaluate.
     * @param list<string> $sql        The sequence of table alteration statements to fill.
     * @param list<string> $queryParts The sequence of column alteration clauses to fill.
     */
    private function gatherAlterColumnSQL(
        string $table,
        ColumnDiff $columnDiff,
        array &$sql,
        array &$queryParts,
        bool &$needsReorg,
    ): void {
        $alterColumnClauses = $this->getAlterColumnClausesSQL($columnDiff, $needsReorg);

        if (count($alterColumnClauses) < 1) {
            return;
        }

        // If we have a single column alteration, we can append the clause to the main query.
        if (count($alterColumnClauses) === 1) {
            $queryParts[] = current($alterColumnClauses);

            return;
        }

        // We have multiple alterations for the same column,
        // so we need to trigger a complete ALTER TABLE statement
        // for each ALTER COLUMN clause.
        foreach ($alterColumnClauses as $alterColumnClause) {
            $sql[] = 'ALTER TABLE ' . $table . ' ' . $alterColumnClause;
        }
    }

    /**
     * Returns the ALTER COLUMN SQL clauses for altering a column described by the given column diff.
     *
     * @return string[]
     */
    private function getAlterColumnClausesSQL(ColumnDiff $columnDiff, bool &$needsReorg): array
    {
        $newColumn   = $columnDiff->getNewColumn();
        $columnArray = $newColumn->toArray();

        $newName = $columnDiff->getNewColumn()->getObjectName()->toSQL($this);
        $oldName = $columnDiff->getOldColumn()->getObjectName()->toSQL($this);

        $alterClause = 'ALTER COLUMN ' . $newName;

        if ($newColumn->getColumnDefinition() !== null) {
            $needsReorg = true;

            return [$alterClause . ' ' . $newColumn->getColumnDefinition()];
        }

        $clauses = [];

        if ($columnDiff->hasNameChanged()) {
            $clauses[] = 'RENAME COLUMN ' . $oldName . ' TO ' . $newName;
        }

        if (
            $columnDiff->hasTypeChanged() ||
            $columnDiff->hasLengthChanged() ||
            $columnDiff->hasPrecisionChanged() ||
            $columnDiff->hasScaleChanged() ||
            $columnDiff->hasFixedChanged()
        ) {
            $needsReorg = true;
            $clauses[]  = $alterClause . ' SET DATA TYPE ' . $newColumn->getType()
                    ->getSQLDeclaration($columnArray, $this);
        }

        if ($columnDiff->hasNotNullChanged()) {
            $needsReorg = true;
            $clauses[]  = $newColumn->getNotnull() ? $alterClause . ' SET NOT NULL' : $alterClause . ' DROP NOT NULL';
        }

        if ($columnDiff->hasDefaultChanged()) {
            if ($newColumn->getDefault() !== null) {
                $defaultClause = $this->getDefaultValueDeclarationSQL($columnArray);

                if ($defaultClause !== '') {
                    $needsReorg = true;
                    $clauses[]  = $alterClause . ' SET' . $defaultClause;
                }
            } else {
                $needsReorg = true;
                $clauses[]  = $alterClause . ' DROP DEFAULT';
            }
        }

        return $clauses;
    }

    #[Override]
    protected function getDefaultValueDeclarationSQL(array $column): string
    {
        if (isset($column['autoincrement']) && $column['autoincrement'] === true) {
            return '';
        }

        return parent::getDefaultValueDeclarationSQL($column);
    }

    #[Override]
    public function getEmptyIdentityInsertSQL(string $quotedTableName, string $quotedIdentifierColumnName): string
    {
        return 'INSERT INTO ' . $quotedTableName . ' (' . $quotedIdentifierColumnName . ') VALUES (DEFAULT)';
    }

    #[Override]
    public function getCreateTemporaryTableSnippetSQL(): string
    {
        return 'DECLARE GLOBAL TEMPORARY TABLE';
    }

    #[Override]
    public function getTemporaryTableName(string $tableName): string
    {
        return 'SESSION.' . $tableName;
    }

    #[Override]
    protected function doModifyLimitQuery(string $query, ?int $limit, int $offset): string
    {
        if ($offset > 0) {
            $query .= sprintf(' OFFSET %d ROWS', $offset);
        }

        if ($limit !== null) {
            $query .= sprintf(' FETCH NEXT %d ROWS ONLY', $limit);
        }

        return $query;
    }

    #[Override]
    public function getLocateExpression(string $string, string $substring, ?string $start = null): string
    {
        if ($start === null) {
            return sprintf('LOCATE(%s, %s)', $substring, $string);
        }

        return sprintf('LOCATE(%s, %s, %s)', $substring, $string, $start);
    }

    #[Override]
    public function getSubstringExpression(string $string, string $start, ?string $length = null): string
    {
        if ($length === null) {
            return sprintf('SUBSTR(%s, %s)', $string, $start);
        }

        return sprintf('SUBSTR(%s, %s, %s)', $string, $start, $length);
    }

    #[Override]
    public function getLengthExpression(string $string): string
    {
        return 'LENGTH(' . $string . ', CODEUNITS32)';
    }

    #[Override]
    public function getCurrentDatabaseExpression(): string
    {
        return 'CURRENT_USER';
    }

    #[Override]
    public function supportsIdentityColumns(): bool
    {
        return true;
    }

    #[Override]
    public function createSelectSQLBuilder(): SelectSQLBuilder
    {
        return new DefaultSelectSQLBuilder($this, 'WITH RR USE AND KEEP UPDATE LOCKS', null);
    }

    #[Override]
    public function getDummySelectSQL(string $expression = '1'): string
    {
        return sprintf('SELECT %s FROM sysibm.sysdummy1', $expression);
    }

    /**
     * Db2 supports savepoints, but they work semantically different than on other vendor platforms.
     *
     * TODO: We have to investigate how to get Db2 up and running with savepoints.
     */
    #[Override]
    public function supportsSavepoints(): bool
    {
        return false;
    }

    #[Override]
    public function createMetadataProvider(Connection $connection): Db2MetadataProvider
    {
        return new Db2MetadataProvider($connection, $this);
    }

    #[Override]
    public function createSchemaManager(Connection $connection): DB2SchemaManager
    {
        return new DB2SchemaManager($connection, $this);
    }
}
