FROM debian:experimental-20180426

RUN apt-get update && \
    apt-get install -y -t experimental --no-install-recommends \
    postgresql-11 \
    postgresql-client-11 \
    && \
    rm -rf /var/lib/apt/lists/*

RUN echo "host all all all trust" >> /etc/postgresql/11/main/pg_hba.conf
RUN echo "listen_addresses='*'" >> /etc/postgresql/11/main/conf.d/listen.conf

EXPOSE 5432

CMD ["sleep", "inf"]
