<?php

declare(strict_types=1);

namespace Doctrine\DBAL\Schema;

use Doctrine\DBAL\Schema\Exception\InvalidUniqueConstraintDefinition;
use Doctrine\DBAL\Schema\Name\UnqualifiedName;
use Doctrine\DBAL\Schema\Name\UnquotedIdentifierFolding;
use Override;

use function array_all;
use function count;

/**
 * Represents unique constraint definition.
 *
 * @implements OptionallyNamedObject<UnqualifiedName>
 */
final readonly class UniqueConstraint implements OptionallyNamedObject
{
    /**
     * @internal Use {@link UniqueConstraint::editor()} to instantiate an editor and
     *           {@link UniqueConstraintEditor::create()} to create a unique constraint.
     *
     * @param ?UnqualifiedName                $name        Name of the unique constraint. If omitted, the name will be
     *                                                     generated by the underlying database platform. To facilitate
     *                                                     managing the constraint using DBAL, specifying the name
     *                                                     explicitly is recommended.
     * @param non-empty-list<UnqualifiedName> $columnNames Names of the columns covered by the unique constraint.
     */
    public function __construct(
        private ?UnqualifiedName $name,
        private array $columnNames,
        private bool $isClustered,
    ) {
        if (count($columnNames) < 1) {
            throw InvalidUniqueConstraintDefinition::columnNamesAreNotSet($name);
        }
    }

    #[Override]
    public function getObjectName(): ?UnqualifiedName
    {
        return $this->name;
    }

    /**
     * Returns the names of the columns the constraint is associated with.
     *
     * @return non-empty-list<UnqualifiedName>
     */
    public function getColumnNames(): array
    {
        return $this->columnNames;
    }

    /**
     * Returns whether the unique constraint is clustered.
     */
    public function isClustered(): bool
    {
        return $this->isClustered;
    }

    public function equals(self $other, UnquotedIdentifierFolding $folding): bool
    {
        if ($this === $other) {
            return true;
        }

        if ($this->isClustered !== $other->isClustered) {
            return false;
        }

        if ($this->name !== null && $other->name !== null && ! $this->name->equals($other->name, $folding)) {
            return false;
        }

        if (count($this->columnNames) !== count($other->columnNames)) {
            return false;
        }

        return array_all(
            $this->columnNames,
            static fn ($columnName, $i) => $columnName->equals($other->columnNames[$i], $folding),
        );
    }

    /**
     * Instantiates a new unique constraint editor.
     */
    public static function editor(): UniqueConstraintEditor
    {
        return new UniqueConstraintEditor();
    }

    /**
     * Instantiates a new unique constraint editor and initializes it with the constraint's properties.
     */
    public function edit(): UniqueConstraintEditor
    {
        return self::editor()
            ->setName($this->name)
            ->setColumnNames(...$this->columnNames)
            ->setIsClustered($this->isClustered);
    }
}
